version: '2'
services:
    webnode:
        extends:
            file: ./base.yml
            service: webnode
        ports:
            - '8080:80'
            - '55443:443'
        labels:
            localhost:8080/admin: 'Backend'
            localhost:8080/: 'Frontend'
